spring.application.name=ani-kafka-microservice
# Connect to your local kafka broker
spring.kafka.bootstrap-servers=localhost:9092
# Convert keys and values into byte arrays before sending
#Spring Boot automatically detects properties prefixed with spring.kafka.producer.*
# and builds the required ProducerFactory and KafkaTemplate beans behind the scenes.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#Spring Boot automatically detects properties prefixed with spring.kafka.producer.*
# and builds the required ConsumerFactory and ConcurrentKafkaListenerContainerFactory beans behind the scenes.
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer